### ISSUE TITLE
Warning: include(): Filename cannot be empty  in app/code/core/Mage/Core/Block/Template.php on line 241

### ISSUE THREAD

**Issue by paales** [mollie/Magento#30]
```
#0 app/code/core/Mage/Core/Block/Template.php(241): mageCoreErrorHandler(2, 'include(): Filename cannot be empty', 'app/code/core/Mage/Core/Block/Template.php', 241, Array)
#1 app/code/core/Mage/Core/Block/Template.php(241): Mage_Core_Block_Template->fetchView()
#2 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/base/default/template/mollie/form/details.phtml')
#3 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#4 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#5 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#6 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('payment.method.mpm_void_00', true)
#7 app/design/adminhtml/default/default/template/sales/order/create/billing/method/form.phtml(46): Mage_Core_Block_Abstract->getChildHtml('payment.method.mpm_void_00')
#8 app/code/core/Mage/Core/Block/Template.php(241): include('app/design/adminhtml/default/default/template/sales/order/create/billing/method/form.phtml')
#9 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/default/default/template/sales/order/create/billing/method/form.phtml')
#10 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#11 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#12 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#13 app/code/core/Mage/Core/Block/Abstract.php(577): Mage_Core_Block_Abstract->_getChildHtml('form', true)
#14 app/design/adminhtml/default/default/template/sales/order/create/abstract.phtml(33): Mage_Core_Block_Abstract->getChildHtml('', true, true)
#15 app/code/core/Mage/Core/Block/Template.php(241): include('app/design/adminhtml/default/default/template/sales/order/create/abstract.phtml')
#16 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/default/default/template/sales/order/create/abstract.phtml')
#17 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#18 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#19 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#20 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#21 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('billing_method', true)
#22 app/design/adminhtml/default/default/template/sales/order/create/data.phtml(56): Mage_Core_Block_Abstract->getChildHtml('billing_method')
#23 app/code/core/Mage/Core/Block/Template.php(241): include('app/design/adminhtml/default/default/template/sales/order/create/data.phtml')
#24 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/default/default/template/sales/order/create/data.phtml')
#25 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#26 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#27 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#28 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#29 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('data', true)
#30 app/design/adminhtml/default/default/template/sales/order/create/form.phtml(45): Mage_Core_Block_Abstract->getChildHtml('data')
#31 app/code/core/Mage/Core/Block/Template.php(241): include('app/design/adminhtml/default/default/template/sales/order/create/form.phtml')
#32 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/default/default/template/sales/order/create/form.phtml')
#33 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#34 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#35 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#36 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#37 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('form', true)
#38 app/code/core/Mage/Adminhtml/Block/Widget/Form/Container.php(130): Mage_Core_Block_Abstract->getChildHtml('form')
#39 app/code/core/Mage/Adminhtml/Block/Sales/Order/Create.php(104): Mage_Adminhtml_Block_Widget_Form_Container->getFormHtml()
#40 app/design/adminhtml/default/default/template/widget/form/container.phtml(37): Mage_Adminhtml_Block_Sales_Order_Create->getFormHtml()
#41 app/code/core/Mage/Core/Block/Template.php(241): include('app/design/adminhtml/default/default/template/widget/form/container.phtml')
#42 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/default/default/template/widget/form/container.phtml')
#43 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#44 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#45 app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#46 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#47 app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#48 app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#49 app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#50 app/code/core/Mage/Core/Block/Template.php(241): include('app/design/adminhtml/default/default/template/page.phtml')
#51 app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/default/default/template/page.phtml')
#52 app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#53 app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#54 app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#55 app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#56 app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#57 app/code/core/Mage/Adminhtml/controllers/Sales/Order/CreateController.php(341): Mage_Core_Controller_Varien_Action->renderLayout()
#58 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_Order_CreateController->indexAction()
#59 .modman/Ho_Patches/app/code/community/Mage/Core/Controller/Varien/Router/Standard.php(283): Mage_Core_Controller_Varien_Action->dispatch('index')
#60 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Mage_Core_Controller_Request_Http)
#61 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#62 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#63 index.php(87): Mage::run('', 'store')
```

**Comment by paetor** [comment]
It looks like the plugin didn't install correctly. Could you try to remove and reinstall the plugin and see if things improve?

**Comment by paales** [comment]
@paetor The module seems to be missing a template, which is also missing in this repository.

**Comment by Daanvm** [comment]
Maybe you can send an email if this is still a problem. We haven't heard this issue from others, so it's probably something specific to your website.
